WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO ON
SET SERVEROUTPUT ON

ALTER SESSION SET CONTAINER=FREEPDB1;

BEGIN
  FOR item IN (
    SELECT column_value AS username
      FROM TABLE(SYS.ODCIVARCHAR2LIST('CBSAC', 'CBSCM', 'CBSLN'))
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP USER ' || item.username || ' CASCADE';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE USER ' || item.username
      || ' IDENTIFIED BY "DbStudio123" DEFAULT TABLESPACE USERS '
      || 'TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, '
      || 'CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO ' || item.username;
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ' || item.username;
  END LOOP;
END;
/

CREATE OR REPLACE DIRECTORY DBSTUDIO_BFILE_DIR AS '/opt/oracle/dbstudio-bfiles';
GRANT READ ON DIRECTORY DBSTUDIO_BFILE_DIR TO CBSAC, CBSCM, CBSLN;

PROMPT Created CBSAC, CBSCM and CBSLN schemas.
