WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO ON
SET SERVEROUTPUT ON

CONNECT CBSAC/DbStudio123@//localhost:1521/FREEPDB1

CREATE TYPE ADDRESS_OBJ AS OBJECT (
  PROVINCE VARCHAR2(40 CHAR),
  CITY VARCHAR2(40 CHAR),
  STREET NVARCHAR2(100)
);
/

CREATE TYPE PHONE_VARRAY AS VARRAY(5) OF VARCHAR2(32 CHAR);
/

CREATE TYPE TAG_NESTED_TABLE AS TABLE OF VARCHAR2(64 CHAR);
/

CREATE TYPE CUSTOMER_OBJ AS OBJECT (
  ID NUMBER(18),
  NAME NVARCHAR2(100)
);
/

CREATE TABLE DATA_TYPE_SHOWCASE (
  ID NUMBER(18) PRIMARY KEY,
  NUMBER_VALUE NUMBER,
  DECIMAL_VALUE DECIMAL(18,4),
  NUMERIC_VALUE NUMERIC(18,4),
  INTEGER_VALUE INTEGER,
  INT_VALUE INT,
  SMALLINT_VALUE SMALLINT,
  FLOAT_VALUE FLOAT(126),
  REAL_VALUE REAL,
  DOUBLE_VALUE DOUBLE PRECISION,
  BINARY_FLOAT_VALUE BINARY_FLOAT,
  BINARY_DOUBLE_VALUE BINARY_DOUBLE,
  CHAR_VALUE CHAR(10 CHAR),
  VARCHAR_VALUE VARCHAR(100 CHAR),
  VARCHAR2_VALUE VARCHAR2(100 CHAR),
  NCHAR_VALUE NCHAR(10),
  NVARCHAR2_VALUE NVARCHAR2(100),
  DATE_VALUE DATE,
  TIMESTAMP_VALUE TIMESTAMP(6),
  TIMESTAMP_TZ_VALUE TIMESTAMP(6) WITH TIME ZONE,
  TIMESTAMP_LTZ_VALUE TIMESTAMP(6) WITH LOCAL TIME ZONE,
  INTERVAL_YM_VALUE INTERVAL YEAR(4) TO MONTH,
  INTERVAL_DS_VALUE INTERVAL DAY(3) TO SECOND(6),
  RAW_VALUE RAW(64),
  ROWID_VALUE ROWID,
  UROWID_VALUE UROWID,
  CLOB_VALUE CLOB,
  NCLOB_VALUE NCLOB,
  BLOB_VALUE BLOB,
  BFILE_VALUE BFILE,
  XML_VALUE XMLTYPE,
  JSON_VALUE JSON,
  BOOLEAN_VALUE BOOLEAN,
  VECTOR_VALUE VECTOR(3, FLOAT32),
  ANYDATA_VALUE SYS.ANYDATA,
  ADDRESS_VALUE ADDRESS_OBJ,
  PHONES_VALUE PHONE_VARRAY,
  TAGS_VALUE TAG_NESTED_TABLE
) NESTED TABLE TAGS_VALUE STORE AS DATA_TYPE_SHOWCASE_TAGS;

COMMENT ON TABLE DATA_TYPE_SHOWCASE IS 'Oracle核心、LOB、对象关系及23ai类型覆盖表';

INSERT INTO DATA_TYPE_SHOWCASE (
  ID, NUMBER_VALUE, DECIMAL_VALUE, NUMERIC_VALUE, INTEGER_VALUE, INT_VALUE,
  SMALLINT_VALUE, FLOAT_VALUE, REAL_VALUE, DOUBLE_VALUE, BINARY_FLOAT_VALUE,
  BINARY_DOUBLE_VALUE, CHAR_VALUE, VARCHAR_VALUE, VARCHAR2_VALUE, NCHAR_VALUE,
  NVARCHAR2_VALUE, DATE_VALUE, TIMESTAMP_VALUE, TIMESTAMP_TZ_VALUE,
  TIMESTAMP_LTZ_VALUE, INTERVAL_YM_VALUE, INTERVAL_DS_VALUE, RAW_VALUE,
  ROWID_VALUE, UROWID_VALUE, CLOB_VALUE, NCLOB_VALUE, BLOB_VALUE, BFILE_VALUE, XML_VALUE,
  JSON_VALUE, BOOLEAN_VALUE, VECTOR_VALUE, ANYDATA_VALUE, ADDRESS_VALUE,
  PHONES_VALUE, TAGS_VALUE
)
SELECT
  1, 123456789.1234, 1234.5678, 9876.5432, 42, 43, 7,
  3.1415926, 2.71828, 1.41421, 1.25f, 2.5d,
  'CHAR', 'VARCHAR', 'VARCHAR2', N'NCHAR', N'中文NVARCHAR2',
  DATE '2026-07-22', TIMESTAMP '2026-07-22 12:34:56.123456',
  TIMESTAMP '2026-07-22 12:34:56.123456 +08:00',
  TIMESTAMP '2026-07-22 12:34:56.123456',
  INTERVAL '2-6' YEAR TO MONTH, INTERVAL '3 04:05:06.123456' DAY TO SECOND,
  HEXTORAW('444253545544494F'), ROWID, ROWID,
  TO_CLOB('DBStudio CLOB 中文'), TO_NCLOB(N'DBStudio NCLOB 中文'),
  TO_BLOB(HEXTORAW('01020304')), BFILENAME('DBSTUDIO_BFILE_DIR', 'sample.txt'),
  XMLTYPE('<dbstudio><provider>oracle</provider></dbstudio>'),
  JSON('{"source":"dbstudio","valid":true}'), TRUE,
  TO_VECTOR('[1.25, 2.5, 3.75]'), SYS.ANYDATA.CONVERTVARCHAR2('DBStudio ANYDATA'),
  ADDRESS_OBJ('广东省', '东莞市', N'测试路1号'),
  PHONE_VARRAY('13800000000', '13900000000'),
  TAG_NESTED_TABLE('oracle', 'dbstudio', '中文')
FROM APP_CONFIG
WHERE ID = 1;

CREATE TABLE LEGACY_LONG_VALUES (
  ID NUMBER PRIMARY KEY,
  LONG_VALUE LONG
);
INSERT INTO LEGACY_LONG_VALUES VALUES (1, 'Oracle legacy LONG value');

CREATE TABLE LEGACY_LONG_RAW_VALUES (
  ID NUMBER PRIMARY KEY,
  LONG_RAW_VALUE LONG RAW
);
INSERT INTO LEGACY_LONG_RAW_VALUES VALUES (1, UTL_RAW.CAST_TO_RAW('legacy binary value'));

CREATE TABLE CUSTOMER_OBJECTS OF CUSTOMER_OBJ (
  CONSTRAINT CUSTOMER_OBJECTS_PK PRIMARY KEY (ID)
) OBJECT IDENTIFIER IS PRIMARY KEY;
INSERT INTO CUSTOMER_OBJECTS VALUES (CUSTOMER_OBJ(1, N'对象客户'));

CREATE TABLE CUSTOMER_REF_VALUES (
  ID NUMBER PRIMARY KEY,
  CUSTOMER_POINTER REF CUSTOMER_OBJ SCOPE IS CUSTOMER_OBJECTS
);
INSERT INTO CUSTOMER_REF_VALUES
SELECT 1, REF(customer) FROM CUSTOMER_OBJECTS customer WHERE customer.ID = 1;

COMMIT;

PROMPT Created Oracle data type showcase in CBSAC.
