WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO ON

CONNECT CBSAC/DbStudio123@//localhost:1521/FREEPDB1
CREATE SEQUENCE DOC_SEQUENCE START WITH 100000 INCREMENT BY 1 CACHE 50;
CREATE VIEW ACTIVE_BUSINESS_OBJECTS AS SELECT ID, BIZ_CODE, DISPLAY_NAME, CREATED_AT FROM APP_CONFIG WHERE STATUS = 'A';
CREATE SYNONYM BUSINESS_OBJECTS FOR APP_CONFIG;
CREATE INDEX SALES_ORDERS_STATUS_IX ON SALES_ORDERS (STATUS, CREATED_AT);
CREATE OR REPLACE PROCEDURE ARCHIVE_AUDIT(P_BEFORE IN TIMESTAMP) AS
BEGIN
  DELETE FROM AUDIT_LOGS WHERE CREATED_AT < P_BEFORE;
END;
/
CREATE OR REPLACE FUNCTION CALC_TAX(P_AMOUNT IN NUMBER) RETURN NUMBER DETERMINISTIC AS
BEGIN
  RETURN ROUND(NVL(P_AMOUNT, 0) * 0.06, 2);
END;
/
CREATE OR REPLACE PACKAGE DEMO_API AS
  FUNCTION SCHEMA_NAME RETURN VARCHAR2;
END DEMO_API;
/
CREATE OR REPLACE PACKAGE BODY DEMO_API AS
  FUNCTION SCHEMA_NAME RETURN VARCHAR2 IS
  BEGIN
    RETURN SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA');
  END;
END DEMO_API;
/
CREATE OR REPLACE TRIGGER SALES_ORDERS_BI
BEFORE INSERT ON SALES_ORDERS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DOC_SEQUENCE.NEXTVAL;
END;
/

CONNECT CBSCM/DbStudio123@//localhost:1521/FREEPDB1
CREATE SEQUENCE DOC_SEQUENCE START WITH 100000 INCREMENT BY 1 CACHE 50;
CREATE VIEW ACTIVE_BUSINESS_OBJECTS AS SELECT ID, BIZ_CODE, DISPLAY_NAME, CREATED_AT FROM APP_CONFIG WHERE STATUS = 'A';
CREATE SYNONYM BUSINESS_OBJECTS FOR APP_CONFIG;
CREATE INDEX SALES_ORDERS_STATUS_IX ON SALES_ORDERS (STATUS, CREATED_AT);
CREATE OR REPLACE PROCEDURE ARCHIVE_AUDIT(P_BEFORE IN TIMESTAMP) AS
BEGIN
  DELETE FROM AUDIT_LOGS WHERE CREATED_AT < P_BEFORE;
END;
/
CREATE OR REPLACE FUNCTION CALC_TAX(P_AMOUNT IN NUMBER) RETURN NUMBER DETERMINISTIC AS
BEGIN
  RETURN ROUND(NVL(P_AMOUNT, 0) * 0.06, 2);
END;
/
CREATE OR REPLACE PACKAGE DEMO_API AS
  FUNCTION SCHEMA_NAME RETURN VARCHAR2;
END DEMO_API;
/
CREATE OR REPLACE PACKAGE BODY DEMO_API AS
  FUNCTION SCHEMA_NAME RETURN VARCHAR2 IS
  BEGIN
    RETURN SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA');
  END;
END DEMO_API;
/
CREATE OR REPLACE TRIGGER SALES_ORDERS_BI
BEFORE INSERT ON SALES_ORDERS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DOC_SEQUENCE.NEXTVAL;
END;
/

CONNECT CBSLN/DbStudio123@//localhost:1521/FREEPDB1
CREATE SEQUENCE DOC_SEQUENCE START WITH 100000 INCREMENT BY 1 CACHE 50;
CREATE VIEW ACTIVE_BUSINESS_OBJECTS AS SELECT ID, BIZ_CODE, DISPLAY_NAME, CREATED_AT FROM APP_CONFIG WHERE STATUS = 'A';
CREATE SYNONYM BUSINESS_OBJECTS FOR APP_CONFIG;
CREATE INDEX SALES_ORDERS_STATUS_IX ON SALES_ORDERS (STATUS, CREATED_AT);
CREATE OR REPLACE PROCEDURE ARCHIVE_AUDIT(P_BEFORE IN TIMESTAMP) AS
BEGIN
  DELETE FROM AUDIT_LOGS WHERE CREATED_AT < P_BEFORE;
END;
/
CREATE OR REPLACE FUNCTION CALC_TAX(P_AMOUNT IN NUMBER) RETURN NUMBER DETERMINISTIC AS
BEGIN
  RETURN ROUND(NVL(P_AMOUNT, 0) * 0.06, 2);
END;
/
CREATE OR REPLACE PACKAGE DEMO_API AS
  FUNCTION SCHEMA_NAME RETURN VARCHAR2;
END DEMO_API;
/
CREATE OR REPLACE PACKAGE BODY DEMO_API AS
  FUNCTION SCHEMA_NAME RETURN VARCHAR2 IS
  BEGIN
    RETURN SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA');
  END;
END DEMO_API;
/
CREATE OR REPLACE TRIGGER SALES_ORDERS_BI
BEFORE INSERT ON SALES_ORDERS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DOC_SEQUENCE.NEXTVAL;
END;
/

COMMIT;
PROMPT Created views, indexes, sequences, synonyms, procedures, functions, packages and triggers.
